"""aggiunta colonna id_evento in laboratori

Revision ID: 26acbbf03e83
Revises: 78dcdc5c11c9
Create Date: 2026-06-21 14:45:45.994181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26acbbf03e83'
down_revision = '78dcdc5c11c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratori', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_evento', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratori', schema=None) as batch_op:
        batch_op.drop_column('id_evento')

    # ### end Alembic commands ###
