"""init db

Revision ID: 78dcdc5c11c9
Revises: 
Create Date: 2026-06-20 23:04:08.417188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78dcdc5c11c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laboratori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posti', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partecipanti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cognome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_option',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('iscrizioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('partecipante', sa.Integer(), nullable=False),
    sa.Column('scelta_mattino', sa.Integer(), nullable=False),
    sa.Column('scelta_pomeriggio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partecipante'], ['partecipanti.id'], name='fk_iscrizioni_partecipanti_id'),
    sa.ForeignKeyConstraint(['scelta_mattino'], ['laboratori.id'], name='fk_iscrizioni_laboratori_mattino_id'),
    sa.ForeignKeyConstraint(['scelta_pomeriggio'], ['laboratori.id'], name='fk_iscrizioni_laboratori_pomeriggio_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iscrizioni')
    op.drop_table('user')
    op.drop_table('system_option')
    op.drop_table('partecipanti')
    op.drop_table('laboratori')
    # ### end Alembic commands ###
