"""aggiunta colonna tipologia in laboratori

Revision ID: 84028c5fc5ed
Revises: 26acbbf03e83
Create Date: 2026-06-21 14:56:37.085286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84028c5fc5ed'
down_revision = '26acbbf03e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratori', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_lab', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('tipologia', sa.String(length=10), nullable=False))
        batch_op.drop_column('id_evento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratori', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_evento', mysql.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('tipologia')
        batch_op.drop_column('id_lab')

    # ### end Alembic commands ###
